name = "jobsdairy"
main = ".open-next/worker.js"
compatibility_date = "2026-05-14"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "jobsdairy"

[[d1_databases]]
binding = "DB"
database_name = "jobdairy-db"
database_id = "0db778d1-ab36-4214-82b8-4f35570515b2"

[[r2_buckets]]
binding = "RESUMES"
bucket_name = "jobdairy-files"
