name = "jobdairy-worker"
main = "worker/src/index.ts"
compatibility_date = "2026-05-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "jobdairy-db"
database_id = "0db778d1-ab36-4214-82b8-4f35570515b2"

[[r2_buckets]]
binding = "RESUMES"
bucket_name = "jobdairy-files"
